name: Docker Image Nightly Release

# Run "nightly" build on each commit to "dev" branch.
on:
  push:
    branches:
      - dev

jobs:
  deploy-docker:
    name: Build Release
    runs-on: ubuntu-latest
    env:
      VERSION: nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=nightly
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ fromJson('["linux/amd64","linux/arm64/v8"]') }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: scripts/docker/alpine/Dockerfile
